package com.hastaa.datausagemonitor.ui.theme

import androidx.compose.ui.graphics.Color

// Material Design 3 Expressive Palette - Light
val md_theme_light_primary = Color(0xFF00687A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFABEDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F26)
val md_theme_light_secondary = Color(0xFF4B626A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE7F0)
val md_theme_light_onSecondaryContainer = Color(0xFF061E25)
val md_theme_light_tertiary = Color(0xFF5C5B7E)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE2DFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF191837)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FAFC)
val md_theme_light_onBackground = Color(0xFF171D1E)
val md_theme_light_surface = Color(0xFFF6FAFC)
val md_theme_light_onSurface = Color(0xFF171D1E)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
val md_theme_light_outline = Color(0xFF70797B)
val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
val md_theme_light_surfaceDim = Color(0xFFD6DBDD)
val md_theme_light_surfaceBright = Color(0xFFF6FAFC)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF0F4F6)
val md_theme_light_surfaceContainer = Color(0xFFEAEEF0)
val md_theme_light_surfaceContainerHigh = Color(0xFFE5E9EA)
val md_theme_light_surfaceContainerHighest = Color(0xFFDFE3E5)

// Material Design 3 Expressive Palette - Dark
val md_theme_dark_primary = Color(0xFF53D7F2)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_primaryContainer = Color(0xFF004E5C)
val md_theme_dark_onPrimaryContainer = Color(0xFFABEDFF)
val md_theme_dark_secondary = Color(0xFFB2CBD4)
val md_theme_dark_onSecondary = Color(0xFF1D343B)
val md_theme_dark_secondaryContainer = Color(0xFF334A52)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE7F0)
val md_theme_dark_tertiary = Color(0xFFC5C3EA)
val md_theme_dark_onTertiary = Color(0xFF2E2D4D)
val md_theme_dark_tertiaryContainer = Color(0xFF444365)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2DFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0E1416)
val md_theme_dark_onBackground = Color(0xFFDEE3E5)
val md_theme_dark_surface = Color(0xFF0E1416)
val md_theme_dark_onSurface = Color(0xFFDEE3E5)
val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
val md_theme_dark_outline = Color(0xFF899295)
val md_theme_dark_outlineVariant = Color(0xFF3F484B)
val md_theme_dark_surfaceDim = Color(0xFF0E1416)
val md_theme_dark_surfaceBright = Color(0xFF343A3C)
val md_theme_dark_surfaceContainerLowest = Color(0xFF090F11)
val md_theme_dark_surfaceContainerLow = Color(0xFF171D1E)
val md_theme_dark_surfaceContainer = Color(0xFF1B2122)
val md_theme_dark_surfaceContainerHigh = Color(0xFF252B2D)
val md_theme_dark_surfaceContainerHighest = Color(0xFF303638)
